"""Configuration loader for A_OpenClaw.

Loads configuration from TOML files with environment variable
overrides (prefix: A_OPENCLAW_).

Based on scaffolding generated by Config Manager Factory.
"""

import os
from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_ENV_PREFIX = "A_OPENCLAW_"


def _load_file(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path, "rb") as f:
        return tomllib.load(f)


def _deep_merge(base: dict, override: dict) -> dict:
    result = base.copy()
    for key, value in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def _apply_env_overrides(config: dict, prefix: str = _ENV_PREFIX) -> dict:
    """Override config values with environment variables.

    A_OPENCLAW_LLM_MODEL=gpt-4  ->  config["llm"]["model"] = "gpt-4"
    """
    for key, value in os.environ.items():
        if not key.startswith(prefix):
            continue
        parts = key[len(prefix):].lower().split("_")
        target = config
        for part in parts[:-1]:
            target = target.setdefault(part, {})
        target[parts[-1]] = value
    return config


def load_config(config_path: Path | None = None) -> dict:
    """Load and merge configuration.

    Priority (highest wins):
        1. Environment variables (A_OPENCLAW_*)
        2. Config TOML file

    Args:
        config_path: Override path to config.toml.
                     Defaults to config/config.toml in the project root.

    Returns:
        Merged configuration dict.
    """
    path = config_path or (_PROJECT_ROOT / "config" / "config.toml")
    config = _load_file(path)
    config = _apply_env_overrides(config)
    return config


_VALID_PROVIDERS = {"anthropic", "openai", "ollama", "llamacpp"}
_VALID_ADAPTER_TYPES = {"", "cli", "telegram"}
_VALID_LOG_FORMATS = {"text", "json"}


def validate_config(config: dict) -> list[str]:
    """Validate configuration and return a list of error messages.

    Returns an empty list if the config is valid.
    """
    errors = []

    # LLM section
    llm = config.get("llm", {})
    provider = llm.get("provider", "")
    if provider and provider not in _VALID_PROVIDERS:
        errors.append(
            f"[llm] Unknown provider: {provider!r}. "
            f"Valid: {', '.join(sorted(_VALID_PROVIDERS))}"
        )

    if provider in ("anthropic", "openai") and not llm.get("model"):
        errors.append(f"[llm] No model specified for provider {provider!r}")

    max_tokens = llm.get("max_response_tokens", 4096)
    if not isinstance(max_tokens, int) or max_tokens < 1:
        errors.append(f"[llm] max_response_tokens must be a positive integer, got: {max_tokens}")

    # Memory section
    mem = config.get("memory", {})
    mem_dir = _PROJECT_ROOT / mem.get("directory", "memory")
    if not mem_dir.exists():
        errors.append(f"[memory] directory does not exist: {mem_dir}")

    # Heartbeat section
    hb = config.get("heartbeat", {})
    interval = hb.get("interval_seconds", 300)
    if not isinstance(interval, (int, float)) or interval < 1:
        errors.append(f"[heartbeat] interval_seconds must be >= 1, got: {interval}")

    sources = hb.get("sources", [])
    for i, src in enumerate(sources):
        if not src.get("type"):
            errors.append(f"[heartbeat.sources[{i}]] missing 'type' field")
        if not src.get("name"):
            errors.append(f"[heartbeat.sources[{i}]] missing 'name' field")

    # Adapter section
    adapter = config.get("adapter", {})
    adapter_type = adapter.get("type", "")
    if adapter_type and adapter_type not in _VALID_ADAPTER_TYPES:
        # Not an error — could be a custom adapter, just a warning-level check
        pass

    # Logging section
    log_cfg = config.get("logging", {})
    log_format = log_cfg.get("format", "text")
    if log_format not in _VALID_LOG_FORMATS:
        errors.append(f"[logging] Unknown format: {log_format!r}. Valid: {', '.join(_VALID_LOG_FORMATS)}")

    return errors


def resolve_path(config: dict, key: str) -> Path:
    """Resolve a config path relative to the project root."""
    return _PROJECT_ROOT / config.get("memory", {}).get(key, key)
